
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AFFICHER DPOINTS EGAL ET NOM NOMBRE PROVERBE SI SINON STRING SUPERIEURconseil : condition\n                  | conseil conditioncondition : SI NOM EGAL STRING DPOINTS actions\n                    | SI NOM SUPERIEUR NOMBRE DPOINTS actions\n                    | SINON SI NOM SUPERIEUR NOMBRE DPOINTS actionsactions : AFFICHER PROVERBE\n                | actions ET PROVERBE'
    
_lr_action_items = {'SI':([0,1,2,4,5,17,19,22,23,24,],[3,3,-1,7,-2,-3,-4,-6,-5,-7,]),'SINON':([0,1,2,5,17,19,22,23,24,],[4,4,-1,-2,-3,-4,-6,-5,-7,]),'$end':([1,2,5,17,19,22,23,24,],[0,-1,-2,-3,-4,-6,-5,-7,]),'NOM':([3,7,],[6,10,]),'EGAL':([6,],[8,]),'SUPERIEUR':([6,10,],[9,13,]),'STRING':([8,],[11,]),'NOMBRE':([9,13,],[12,16,]),'DPOINTS':([11,12,16,],[14,15,20,]),'AFFICHER':([14,15,20,],[18,18,18,]),'ET':([17,19,22,23,24,],[21,21,-6,21,-7,]),'PROVERBE':([18,21,],[22,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'conseil':([0,],[1,]),'condition':([0,1,],[2,5,]),'actions':([14,15,20,],[17,19,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> conseil","S'",1,None,None,None),
  ('conseil -> condition','conseil',1,'p_conseil','interface.py',315),
  ('conseil -> conseil condition','conseil',2,'p_conseil','interface.py',316),
  ('condition -> SI NOM EGAL STRING DPOINTS actions','condition',6,'p_condition','interface.py',323),
  ('condition -> SI NOM SUPERIEUR NOMBRE DPOINTS actions','condition',6,'p_condition','interface.py',324),
  ('condition -> SINON SI NOM SUPERIEUR NOMBRE DPOINTS actions','condition',7,'p_condition','interface.py',325),
  ('actions -> AFFICHER PROVERBE','actions',2,'p_actions','interface.py',353),
  ('actions -> actions ET PROVERBE','actions',3,'p_actions','interface.py',354),
]
